// Automatically generated by Opus v0.50
namespace Breakpad
{
    class BreakpadStaticLibrary : C.StaticLibrary
    {
        class SourceFiles : C.CPlusPlus.ObjectFileCollection
        {
            public SourceFiles()
            {
                this.UpdateOptions += new Opus.Core.UpdateOptionCollectionDelegate(SourceFiles_UpdateOptions);
            }

            [C.ExportCompilerOptionsDelegate]
            void SourceFiles_UpdateOptions(Opus.Core.IModule module, Opus.Core.Target target)
            {
                C.ICCompilerOptions compilerOptions = module.Options as C.ICCompilerOptions;
                compilerOptions.IncludePaths.Include(this, "src", "src");
            }
        }

        [Opus.Core.SourceFiles]
        SourceFiles source = new SourceFiles();
    }
}
