// Automatically generated by Opus v0.50
namespace Test
{
    class ConsoleTest : C.Application
    {
        public ConsoleTest()
        {
            this.UpdateOptions += new Opus.Core.UpdateOptionCollectionDelegate(ConsoleTest_UpdateOptions);
        }

        void ConsoleTest_UpdateOptions(Opus.Core.IModule module, Opus.Core.Target target)
        {
            C.ILinkerOptions linkerOptions = module.Options as C.ILinkerOptions;
            linkerOptions.DoNotAutoIncludeStandardLibraries = false;
        }

        class Source : C.CPlusPlus.ObjectFileCollection
        {
            public Source()
            {
                this.Include(this, "src", "*.cpp");
                this.UpdateOptions += new Opus.Core.UpdateOptionCollectionDelegate(Source_UpdateOptions);
            }

            void Source_UpdateOptions(Opus.Core.IModule module, Opus.Core.Target target)
            {
                C.ICCompilerOptions compilerOptions = module.Options as C.ICCompilerOptions;
                compilerOptions.IgnoreStandardIncludePaths = false;
            }
        }

        [Opus.Core.SourceFiles]
        Source source = new Source();

        [Opus.Core.RequiredModules]
        Opus.Core.TypeArray dependencies = new Opus.Core.TypeArray(typeof(WindowsSDK.WindowsSDK));
    }
}
